public class testingassignment2 
{
public static integer add(integer a,integer b)
{
    integer x=a+b;
    system.debug(x);
    return x;
    
}
    public static integer sub(integer a,integer b)
    {
        integer y=a-b;
        return y;
    }
    public static integer mul(integer a,integer b)
    {
        integer z=a*b;
        return z;
    }
    public static integer div(integer a,integer b)
    {
        integer d=a/b;
        return d;
    }
}